# 02 – Pricing
Estimate a price per 100 g for each bar from its rating and cocoa content, then isolate dark chocolates.

## Load preprocessed data

In [15]:
import numpy as np
import pandas as pd

df = pd.read_csv('../data/processed/chocolate_preprocessed.csv')
df.head()

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin
0,A. Morin,Agua Grande,2016,63.0,France,3.75,Blend,Sao Tome
1,A. Morin,Kpime,2015,70.0,France,2.75,Blend,Togo
2,A. Morin,Atsane,2015,70.0,France,3.00,Blend,Togo
3,A. Morin,Akata,2015,70.0,France,3.50,Blend,Togo
4,A. Morin,Quilla,2015,70.0,France,3.50,Blend,Peru

## Rescale ratings
Scale `Rating` so the maximum becomes 100.

In [28]:
a = df['Rating'].max()
df['Rating'] = df['Rating']*100/a
df.head()

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin
0,A. Morin,Agua Grande,2016,63.0,France,75.0,Blend,Sao Tome
1,A. Morin,Kpime,2015,70.0,France,55.0,Blend,Togo
2,A. Morin,Atsane,2015,70.0,France,60.0,Blend,Togo
3,A. Morin,Akata,2015,70.0,France,70.0,Blend,Togo
4,A. Morin,Quilla,2015,70.0,France,70.0,Blend,Peru

## Price per 100 g
`price(100g) = Cocoa Percent × Rating × 25`, so a 100% cocoa, top-rated bar costs 250,000.

In [76]:
df['price(100g)'] = df['Cocoa Percent'] * df['Rating'] * 25
df.head()

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,A. Morin,Agua Grande,2016,63.0,France,75.0,Blend,Sao Tome,118125.0
1,A. Morin,Kpime,2015,70.0,France,55.0,Blend,Togo,96250.0
2,A. Morin,Atsane,2015,70.0,France,60.0,Blend,Togo,105000.0
3,A. Morin,Akata,2015,70.0,France,70.0,Blend,Togo,122500.0
4,A. Morin,Quilla,2015,70.0,France,70.0,Blend,Peru,122500.0

## Select dark chocolates
Dark chocolate is defined as cocoa content > 70%.

In [77]:
dfc = df.copy()
dfc = dfc.rename(columns={'Cocoa Percent':'Percent'})
dark_chocolates = dfc[dfc.Percent > 70].reset_index()
dark_chocolates = dark_chocolates.rename(columns={'Percent':'Cocoa Percent'})
dark_chocolates.drop(['index'], axis=1, inplace=True)
dark_chocolates.head()

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,Adi,"Vanua Levu, Toto-A",2011,80.0,Fiji,65.0,Trinitario,Fiji,130000.0
1,Adi,Vanua Levu,2011,88.0,Fiji,70.0,Trinitario,Fiji,154000.0
2,Adi,"Vanua Levu, Ami-Ami-CA",2011,72.0,Fiji,70.0,Trinitario,Fiji,126000.0
3,Akesson's (Pralus),"Bali (west), Sukrama Family, Melaya area",2011,75.0,Switzerland,75.0,Trinitario,Indonesia,140625.0
4,Akesson's (Pralus),"Madagascar, Ambolikapiky P.",2010,75.0,Switzerland,55.0,Criollo,Madagascar,103125.0

## Trinitario price adjustment
Flag bars whose `Bean Type` contains *Trinitario* and raise their price by 10%.

In [78]:
has_Trinitario = dark_chocolates['Bean Type'].str.contains('Trinitario', na=False)

In [79]:
dark_chocolates.loc[has_Trinitario, 'price(100g)'] *= 1.1
dark_chocolates.head()

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,Adi,"Vanua Levu, Toto-A",2011,80.0,Fiji,65.0,Trinitario,Fiji,143000.0
1,Adi,Vanua Levu,2011,88.0,Fiji,70.0,Trinitario,Fiji,169400.0
2,Adi,"Vanua Levu, Ami-Ami-CA",2011,72.0,Fiji,70.0,Trinitario,Fiji,138600.0
3,Akesson's (Pralus),"Bali (west), Sukrama Family, Melaya area",2011,75.0,Switzerland,75.0,Trinitario,Indonesia,154687.5
4,Akesson's (Pralus),"Madagascar, Ambolikapiky P.",2010,75.0,Switzerland,55.0,Criollo,Madagascar,103125.0

## Total price of dark chocolates

In [80]:
priceSum = dark_chocolates['price(100g)'].sum()

## Save

In [81]:
df.to_csv('../data/processed/chocolate_price.csv', index = False)
dark_chocolates.to_csv('../data/processed/dark_chocolates.csv', index = True)

File Paths:
['answers.npz', 'project1_step2.ipynb', 'chocolate_price.csv', 'dark_chocolates.csv']