# 03 – Best Companies
For non-dark chocolates (cocoa ≤ 70%), find the top-rated companies and the bars they produce.

## Load priced data

In [5]:
import numpy as np
import pandas as pd

df = pd.read_csv('../data/processed/chocolate_price.csv')
df.head()

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,A. Morin,Agua Grande,2016,63.0,France,75.0,Blend,Sao Tome,118125.0
1,A. Morin,Kpime,2015,70.0,France,55.0,Blend,Togo,96250.0
2,A. Morin,Atsane,2015,70.0,France,60.0,Blend,Togo,105000.0
3,A. Morin,Akata,2015,70.0,France,70.0,Blend,Togo,122500.0
4,A. Morin,Quilla,2015,70.0,France,70.0,Blend,Peru,122500.0

## Select non-dark chocolates

In [8]:
df = df.rename(columns={'Cocoa Percent':'Percent'})
df = df[df.Percent <= 70].reset_index()
df = df.rename(columns={'Percent':'Cocoa Percent'})
df.drop(['index'], axis=1, inplace=True)
df.head()

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,A. Morin,Agua Grande,2016,63.0,France,75.0,Blend,Sao Tome,118125.0
1,A. Morin,Kpime,2015,70.0,France,55.0,Blend,Togo,96250.0
2,A. Morin,Atsane,2015,70.0,France,60.0,Blend,Togo,105000.0
3,A. Morin,Akata,2015,70.0,France,70.0,Blend,Togo,122500.0
4,A. Morin,Quilla,2015,70.0,France,70.0,Blend,Peru,122500.0

## Mean rating per company and year
Pivot to a company × review-year table.

In [20]:
companies = df.groupby(['Company','Review Date'])['Rating'].mean().unstack()
companies.head()

Review Date,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
Company,,,,,,,,,,,,
A. Morin,NaN,NaN,NaN,NaN,NaN,NaN,72.5,66.363636,70.0,63.75,75.0,NaN
AMMA,NaN,NaN,NaN,NaN,77.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Acalli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.00,NaN,NaN
Adi,NaN,NaN,NaN,NaN,NaN,55.0,NaN,NaN,NaN,NaN,NaN,NaN
Aequare (Gianduja),NaN,NaN,NaN,57.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
companies.columns.name = None
companies.index.name = None

## Mean rating since 2012
Average each company's yearly ratings from 2012 onward.

In [27]:
mean_ratings = companies.loc[:, 2012:].mean(axis=1)
mean_ratings.head()

A. Morin              69.522727
AMMA                        NaN
Acalli                75.000000
Adi                         NaN
Aequare (Gianduja)          NaN
dtype: float64

## Top 10 companies
Rank by mean rating; ties are broken alphabetically (stable sort on the sorted index).

In [38]:
best_ratings = mean_ratings.sort_values(ascending=False, kind='mergesort')
best_ratings = best_ratings.sort_index(kind='mergesort')
best_ratings = best_ratings.sort_values(ascending=False, kind='mergesort').head(10)
best_ratings

Patric                     80.000000
Tobago Estate (Pralus)     80.000000
Willie's Cacao             80.000000
L.A. Burdick (Felchlin)    77.500000
Matale                     77.500000
Pacari                     77.500000
Valrhona                   76.666667
Acalli                     75.000000
Amedei                     75.000000
Askinosie                  75.000000
dtype: float64

## Chocolates to sell
Select all bars made by the top-10 companies.

In [41]:
chocolates_to_sell = df[df['Company'].isin(best_ratings.index)]
chocolates_to_sell = chocolates_to_sell.reset_index(drop=True)
chocolates_to_sell.head()

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,Acalli,"Chulucanas, El Platanal",2015,70.0,U.S.A.,75.0,Blend,Peru,131250.0
1,Acalli,"Tumbes, Norandino",2015,70.0,U.S.A.,75.0,Criollo,Peru,131250.0
2,Amedei,"Piura, Blanco de Criollo",2012,70.0,Italy,75.0,Blend,Peru,131250.0
3,Amedei,Porcelana,2007,70.0,Italy,80.0,Criollo (Porcelana),Venezuela,140000.0
4,Amedei,Chuao,2007,70.0,Italy,100.0,Trinitario,Venezuela,175000.0

## Total price

In [43]:
priceSum = chocolates_to_sell['price(100g)'].sum()

## Save

In [44]:
df.to_csv('../data/processed/normal_chocolates.csv', index = True)
companies.to_csv('../data/processed/companies.csv', index = True)
chocolates_to_sell.to_csv('../data/processed/chocolates_to_sell.csv', index = True)
mean_ratings.to_csv('../data/processed/mean_ratings.csv', index = True)
best_ratings.to_csv('../data/processed/best_ratings.csv', index = True)

File Paths:
['answers.npz', 'project1_step3.ipynb', 'chocolates_to_sell.csv', 'companies.csv', 'mean_ratings.csv', 'best_ratings.csv', 'normal_chocolates.csv']